#pragma config(Motor,  port1,           arm,           tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[arm] = 127;
	while(true) {
		delay(25);
	}

}
